name: chatbot-clone
region: fra1

jobs:
  - name: sync-articles
    kind: PRE_DEPLOY
    instance_count: 1
    instance_size_slug: basic-xxs
    dockerfile_path: Dockerfile
    
    # Schedule: Run daily at 2:00 AM UTC
    run_command: python main.py
    
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ZENDESK_API_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: USE_DO_SPACES
        scope: RUN_TIME
        value: "true"
      - key: DO_SPACES_BUCKET
        scope: RUN_TIME
        value: "your-bucket-name"
      - key: DO_SPACES_REGION
        scope: RUN_TIME
        value: "nyc3"
      - key: DO_SPACES_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_STATE_KEY
        scope: RUN_TIME
        value: "chatbot-clone/state.json"