name: optibot-scraper
region: nyc

jobs:
- name: daily-scraper
  github:
    repo: vvduth/chatbot-clone
    branch: main
    deploy_on_push: false
  source_dir: /
  dockerfile_path: Dockerfile
  schedule:
    cron: "*/5 * * * *"  # every 5 mins to test at first
  instance_count: 1
  instance_size_slug: basic-xxs  # Minimal resources for scheduled job
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: ZENDESK_API_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: ${ZENDESK_API_TOKEN}
  - key: ZENDESK_EMAIL
    scope: RUN_TIME
    type: SECRET
    value: ${ZENDESK_EMAIL}
  - key: ZENDESK_DOMAIN
    scope: RUN_TIME
    type: GENERAL
    value: support.optisigns.com
  - key: OUTPUT_DIR
    scope: RUN_TIME
    type: GENERAL
    value: data/articles
  - key: STATE_FILE
    scope: RUN_TIME
    type: GENERAL
    value: data/state.json
  volumes:
  - path: /app/data
    name: scraper-state
    mount_path: /app/data
    size_gigabytes: 1
